/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pocket_money_manager;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joydas451
 */
public class costTable extends javax.swing.JFrame {
    
     Connection con=null;
     PreparedStatement pstmt=null;
     ResultSet rst = null;
     
     DefaultTableModel model;
     //int selectedRow=0;
     
     
     

    /**
     * Creates new form costTable
     */
    public costTable() {
        initComponents();
        
        String id = new String();
        id = MainFrame.jTextFieldUserName.getText().trim();
        jLabelName.setText(id);
        
        model = (DefaultTableModel) jTablecost.getModel();
        
//        jTablecost.getColumnModel().getColumn(0).setMinWidth(0);
//        jTablecost.getColumnModel().getColumn(0).setMaxWidth(0);
                
        costtable();
        
    }
    
    public void costtable(){
        
        String id = new String();
        id = MainFrame.jTextFieldUserName.getText().trim();
        
        try{
            
            con = (Connection) DriverManager.getConnection(pocket_money_manager.DB_Connection.db_url, pocket_money_manager.DB_Connection.db_userName, pocket_money_manager.DB_Connection.db_password);
            pstmt=(PreparedStatement) con.prepareStatement("SELECT catagory,cost,date FROM cost WHERE username='"+id+"'");
            
            ResultSet rst = pstmt.executeQuery();
            while(rst.next()){
                
                Object[] obj=new Object[3];
                obj[0]=rst.getString("catagory");
                obj[1]=rst.getInt("cost");
                obj[2]=rst.getDate("date");
                
                model.addRow(obj);
                getsum();
            }
        }
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);

        }
        finally{
        try{
                if(pstmt!=null) pstmt.close();
                if(con!=null)con.close();
            }
                   catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        
    }
    }

    }

    
    public void getsum(){
        
        int rowscount = jTablecost.getRowCount();
        int sum = 0;
        
        for(int i=0; i<rowscount;i++){
            
            sum = sum+Integer.parseInt(jTablecost.getValueAt(i, 1).toString());        
            
            }
        
        jTextFieldTotalCost.setText(Integer.toString(sum));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTotalCost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecost = new javax.swing.JTable();
        jLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Total Cost ::::");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 144, 29));

        jTextFieldTotalCost.setEditable(false);
        jTextFieldTotalCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldTotalCost.setForeground(new java.awt.Color(153, 153, 255));
        jPanel2.add(jTextFieldTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 199, -1));

        jTablecost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTablecost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Cost", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablecost.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jTablecost.setPreferredSize(new java.awt.Dimension(225, 110));
        jTablecost.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTablecost.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(jTablecost);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 570, 198));

        jLabelName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 158, 39));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Total Cost of User :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 125, 39));

        jButtonback.setBackground(new java.awt.Color(0, 51, 255));
        jButtonback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 116, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pocket_money_manager/table.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        dispose();
        CurrentMonth cm = new CurrentMonth();
        cm.setVisible(true);
        cm.setResizable(false);
    }//GEN-LAST:event_jButtonbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(costTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(costTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(costTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(costTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new costTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecost;
    private javax.swing.JTextField jTextFieldTotalCost;
    // End of variables declaration//GEN-END:variables
}
