/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pocket_money_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.xml.transform.Result;

/**
 *
 * @author Mr. JoY
 */
public class MainFrame extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pstmt=null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uUserName = new javax.swing.JLabel();
        uPassword = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldpassword = new javax.swing.JPasswordField();
        jButtonlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonSignup = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login Form");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uUserName.setForeground(new java.awt.Color(255, 0, 0));
        uUserName.setText("User Name : ");
        jPanel1.add(uUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 102, 89, 24));

        uPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uPassword.setForeground(new java.awt.Color(255, 0, 0));
        uPassword.setText("Password :");
        jPanel1.add(uPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 138, 89, -1));

        jTextFieldUserName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 105, 230, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Login Form : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 11, 271, 35));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Please enter your user name and password for sing in :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 52, 367, 24));

        jPasswordFieldpassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(jPasswordFieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 137, 230, -1));

        jButtonlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonlogin.setForeground(new java.awt.Color(0, 255, 0));
        jButtonlogin.setText("Login");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 163, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Forget Password ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 27));

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 102, 102));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("it here..");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 57, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Haven't an account? ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 40));

        jButtonSignup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSignup.setForeground(new java.awt.Color(255, 51, 51));
        jButtonSignup.setText("SignUp");
        jButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pocket_money_manager/welcome.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldUserName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a username..");
            jTextFieldUserName.requestFocus();
        }
        else if(jPasswordFieldpassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter password.");
            jPasswordFieldpassword.requestFocus();
        }
        else{
            login();
        }
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void login(){
        try{
            con = (Connection) DriverManager.getConnection(pocket_money_manager.DB_Connection.db_url, pocket_money_manager.DB_Connection.db_userName, pocket_money_manager.DB_Connection.db_password);
            pstmt=(PreparedStatement) con.prepareStatement("select username,password from usertable where username='"+jTextFieldUserName.getText()+"'");
            
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                String uname = rs.getString("username");
                String pass = rs.getString("password");
                
                if(jTextFieldUserName.getText().trim().equalsIgnoreCase(uname) && jPasswordFieldpassword.getText().equals(pass)){
                    dispose();
                    UserForm uf = new UserForm();
                    uf.setVisible(true);
                    uf.setResizable(false);
                    break;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please enter valid username and password.");
                    jTextFieldUserName.setText(null);
                    jPasswordFieldpassword.setText(null);
                    return;
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);

        }
    }
    
    
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        dispose();
        ResetPass rp = new ResetPass();
        rp.setVisible(true);
        rp.setResizable(false);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupActionPerformed
        // TODO add your handling code here:
        dispose();
        singUp sign = new singUp();
        sign.setVisible(true);
        sign.setResizable(false);
    }//GEN-LAST:event_jButtonSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSignup;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldpassword;
    public static javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JLabel uPassword;
    private javax.swing.JLabel uUserName;
    // End of variables declaration//GEN-END:variables
}
