/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pocket_money_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joydas451
 */
public class ResetPass extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pstmt=null;
    ResultSet rs = null;

    /**
     * Creates new form NewJFrame
     */
    public ResetPass() {
        initComponents();
        
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordFieldconpass = new javax.swing.JPasswordField();
        jPasswordpass = new javax.swing.JPasswordField();
        jTextFieldusername = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reset Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 208, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 74, 26));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("e-mail Adress :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 111, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("User Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 137, 94, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Password :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 79, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPasswordFieldconpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordFieldconpass.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(jPasswordFieldconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 209, -1));

        jPasswordpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordpass.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(jPasswordpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 208, -1));

        jTextFieldusername.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldusername.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jTextFieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 138, 208, -1));

        jTextFieldemail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldemail.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 110, 208, -1));

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pocket_money_manager/funny-cartoon-egg-3d-character-23117639.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldemail.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter user name.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jTextFieldemail.requestFocus();
           return;
       }
        if(jPasswordpass.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter password.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jPasswordpass.requestFocus();
           return;
       }
        if(jPasswordFieldconpass.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter password again.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jPasswordFieldconpass.requestFocus();
           return;
       }
        String pass = new String(jPasswordpass.getPassword());
        String conpass = new String(jPasswordFieldconpass.getPassword());
        
        if(pass.equals(conpass)){
        reset();
        }
        else{
            JOptionPane.showMessageDialog(null,"Password Not Matched..!!");
            jTextFieldusername.setText(null);
            jPasswordFieldconpass.setText(null);
            jPasswordpass.setText(null);
            
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    public void reset(){
        
        try{
            con = (Connection) DriverManager.getConnection(pocket_money_manager.DB_Connection.db_url, pocket_money_manager.DB_Connection.db_userName, pocket_money_manager.DB_Connection.db_password);
           
           pstmt=(PreparedStatement) con.prepareStatement("SELECT username, email FROM `usertable` WHERE username='"+jTextFieldusername.getText().trim()+"'");

           rs = pstmt.executeQuery();
           while(rs.next()){
               String uname = rs.getString("username");
               String mail = rs.getString("email");
               
               if(jTextFieldemail.getText().trim().equals(mail) && jTextFieldusername.getText().trim().equals(uname)){
                   
                 pstmt=(PreparedStatement) con.prepareStatement("UPDATE `usertable` SET `password` = '"+jPasswordpass.getText().trim()+"' WHERE `usertable`.`username` = '"+jTextFieldusername.getText().trim()+"'");
                 
                 int isOK = 0;
                 isOK = pstmt.executeUpdate();
                 
                 if(isOK>0){
                     JOptionPane.showMessageDialog(null, "You have changed your password!!","Confirmation",JOptionPane.INFORMATION_MESSAGE);
                     dispose();
                     MainFrame mf = new MainFrame();
                     mf.setVisible(true);
                     mf.setResizable(false);
                     break;
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "hey bro");
                     break;
                 }
               } 
               else{
                   JOptionPane.showMessageDialog(null, "email and username not matched..!!","Confirmation",JOptionPane.INFORMATION_MESSAGE);
                   jTextFieldName.setText(null);
                   jTextFieldemail.setText(null);
                   jPasswordpass.setText(null);
                   jPasswordFieldconpass.setText(null);
                   
               }
           
           }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);

        }
        finally{
        try{
                if(pstmt!=null) pstmt.close();
                if(con!=null)con.close();
            }
                    catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        
    }
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldconpass;
    private javax.swing.JPasswordField jPasswordpass;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables
}
