/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pocket_money_manager;
import java.util.Calendar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joydas451
 */
public class singUp extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pstmt=null;
    PreparedStatement pstmt1=null;
    PreparedStatement pstmt2=null;
    
    int count = 0;
    

    /**
     * Creates new form singUp
     */
    public singUp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonSingUp = new javax.swing.JButton();
        jTextFieldmobilenumber = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldSingUpUserName = new javax.swing.JTextField();
        jPasswordFieldsingUpPassword = new javax.swing.JPasswordField();
        jPasswordFieldConfirmpass = new javax.swing.JPasswordField();
        jTextFieldsingUpName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 255, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("User Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 121, 24));

        jLabel3.setBackground(new java.awt.Color(0, 255, 51));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 121, 26));

        jLabel4.setBackground(new java.awt.Color(0, 255, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Confirm Password :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 40));

        jLabel5.setBackground(new java.awt.Color(0, 255, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("e-mail adress :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 121, -1));

        jLabel6.setBackground(new java.awt.Color(0, 255, 51));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Mobile Number :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 112, -1));

        jButtonSingUp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSingUp.setForeground(new java.awt.Color(51, 51, 255));
        jButtonSingUp.setText("Sing Up");
        jButtonSingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSingUpActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jTextFieldmobilenumber.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldmobilenumber.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(jTextFieldmobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 317, -1));

        jTextFieldemail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldemail.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 317, -1));

        jTextFieldSingUpUserName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldSingUpUserName.setForeground(new java.awt.Color(102, 255, 0));
        jPanel2.add(jTextFieldSingUpUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 317, -1));

        jPasswordFieldsingUpPassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordFieldsingUpPassword.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jPasswordFieldsingUpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 317, -1));

        jPasswordFieldConfirmpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordFieldConfirmpass.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jPasswordFieldConfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 317, 20));

        jTextFieldsingUpName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldsingUpName.setForeground(new java.awt.Color(102, 255, 0));
        jPanel2.add(jTextFieldsingUpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 317, 20));

        jLabel1.setBackground(new java.awt.Color(0, 255, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Name :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 93, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pocket_money_manager/sing.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 490, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonSingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSingUpActionPerformed
        // TODO add your handling code here:
        String pass = new String(jPasswordFieldsingUpPassword.getPassword());
        String conpass = new String(jPasswordFieldConfirmpass.getPassword());
        
        if(pass.equals(conpass)){
        insertData();
        }
        else{
            JOptionPane.showMessageDialog(null,"Password Not Matched..!!");
        }
    }//GEN-LAST:event_jButtonSingUpActionPerformed

    
    public void insertData()
    {
        ////validation start///
        if(jTextFieldsingUpName.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter Name.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jTextFieldsingUpName.requestFocus();
           return;
       }
       if(jTextFieldSingUpUserName.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter username.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jTextFieldSingUpUserName.requestFocus();
           return;
       } 
       if(jPasswordFieldsingUpPassword.getText().trim().equals("")){
           JOptionPane.showMessageDialog(null, "Please enter password.", "ERROR", JOptionPane.ERROR_MESSAGE);
           jPasswordFieldsingUpPassword.requestFocus();
           return;
       }
       if(jTextFieldemail.getText().equals(null)){
           JOptionPane.showMessageDialog(null, "You must have a mail adress..!!");
       }
        
       
       try{
          
           con = (Connection) DriverManager.getConnection(pocket_money_manager.DB_Connection.db_url, pocket_money_manager.DB_Connection.db_userName, pocket_money_manager.DB_Connection.db_password);
           
           pstmt=(PreparedStatement) con.prepareStatement("SELECT username FROM `usertable` WHERE `username`= '"+jTextFieldSingUpUserName.getText().trim()+"'");
           
           //String sql = "select * from usertable where username=u";
           ResultSet rs = pstmt.executeQuery();
           while(rs.next()){
               //String u = jTextFieldSingUpUserName.getText().trim();
               String name = rs.getString("username");
               if(jTextFieldSingUpUserName.getText().trim().equalsIgnoreCase(name)){
                    count = 1;
                   break;
               }
           }
        if(count == 0){
           pstmt=(PreparedStatement) con.prepareStatement("insert into usertable (name,username,password,email,mobile)"
               + "values(?,?,?,?,?) ");
        
      
            pstmt.setString(1, jTextFieldsingUpName.getText());   
            pstmt.setString(2, jTextFieldSingUpUserName.getText());
            pstmt.setString(3, jPasswordFieldsingUpPassword.getText()); 
            pstmt.setString(4, jTextFieldemail.getText()); 
            pstmt.setString(5, jTextFieldmobilenumber.getText());
            int isOk=0;
            isOk = pstmt.executeUpdate();
            if(isOk>0)
            {   
                String[] monthName = {"January", "February",
                "March", "April", "May", "June", "July",
                "August", "September", "October", "November",
                "December"};
                Calendar cal = Calendar.getInstance();
                String month = monthName[cal.get(Calendar.MONTH)];
                JOptionPane.showMessageDialog(null, "Successfully Registered!!","Confirmation",JOptionPane.INFORMATION_MESSAGE);
                pstmt1=(PreparedStatement) con.prepareStatement("SELECT username FROM `usertable` where username= '"+jTextFieldSingUpUserName.getText().trim()+"'");
                ResultSet rs1 = pstmt1.executeQuery();
                 while(rs1.next()){
                    String name1 = rs1.getString("username");
                    pstmt2=(PreparedStatement) con.prepareStatement("insert into accounts (currentbal,username,month)"
               + "values(?,?,?) ");
                    pstmt2.setInt(1, 0);   
                    pstmt2.setString(2, name1);
                    pstmt2.setString(3,month); 
                    pstmt2.executeUpdate();
            
                 }
                dispose();
                MainFrame mf = new MainFrame();
                mf.setVisible(true);
                mf.setResizable(false);
            }
            }
        else{
            JOptionPane.showMessageDialog(null, "User name is already taken.!!Please try another one... :) ");
            jTextFieldSingUpUserName.setText(null);
            jPasswordFieldsingUpPassword.setText(null);
            jPasswordFieldConfirmpass.setText(null);
            count = 0;
        }
        
        }
        catch(SQLException ex){
      JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
    }
    finally{
        try{
                if(pstmt!=null) pstmt.close();
                if(con!=null)con.close();
            }
                    catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        
    }
    }
       //clearData();
    }
    
    
     private void clearData()
    {
        jTextFieldsingUpName.setText(null);
        jTextFieldSingUpUserName.setText(null);
        jPasswordFieldsingUpPassword.setText(null);
        jTextFieldemail.setText(null);
        jTextFieldmobilenumber.setText(null);
        jPasswordFieldConfirmpass.setText(null);
    }
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new singUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSingUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirmpass;
    private javax.swing.JPasswordField jPasswordFieldsingUpPassword;
    private javax.swing.JTextField jTextFieldSingUpUserName;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldmobilenumber;
    private javax.swing.JTextField jTextFieldsingUpName;
    // End of variables declaration//GEN-END:variables
}
