/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pocket_money_manager;

import com.sun.javafx.geom.CubicApproximator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joydas451
 */
public class UserForm extends javax.swing.JFrame {
    
    Connection con=null;
    PreparedStatement pstmt=null;
    ResultSet rs = null;

    
    public UserForm() {
        initComponents();
        combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtononshow = new javax.swing.JButton();
        jButtonopen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Open a new account for a new month :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 247, 30));

        jComboBoxMonth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBoxMonth.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jComboBoxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 49, 117, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Show details of current month :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, 199, 36));

        jButtononshow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtononshow.setForeground(new java.awt.Color(51, 51, 255));
        jButtononshow.setText("Show");
        jButtononshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtononshowActionPerformed(evt);
            }
        });
        jPanel1.add(jButtononshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 145, 117, -1));

        jButtonopen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonopen.setForeground(new java.awt.Color(51, 255, 204));
        jButtonopen.setText("Open");
        jButtonopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonopenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 93, 117, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pocket_money_manager/Untitled.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtononshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtononshowActionPerformed
        // TODO add your handling code here:        
        dispose();
        CurrentMonth cm = new CurrentMonth();
        cm.setVisible(true);
        cm.setResizable(false);
    }//GEN-LAST:event_jButtononshowActionPerformed

    private void jButtonopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonopenActionPerformed
        // TODO add your handling code here:
        dispose();
        CurrentMonth cm = new CurrentMonth();
        cm.setVisible(true);
        cm.setResizable(false);
    }//GEN-LAST:event_jButtonopenActionPerformed

    public void combo(){
        try{
            
            con = (Connection) DriverManager.getConnection(pocket_money_manager.DB_Connection.db_url, pocket_money_manager.DB_Connection.db_userName, pocket_money_manager.DB_Connection.db_password);
            pstmt=(PreparedStatement) con.prepareStatement("select * from monthtable");
            
            rs = pstmt.executeQuery();
            
            while(rs.next()){
                String name = rs.getString("month");
                
                jComboBoxMonth.addItem(name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        finally{
        try{
                if(pstmt!=null) pstmt.close();
                if(con!=null)con.close();
            }
                    catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error occured due to:\n"+ex.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
        
    }
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtononshow;
    private javax.swing.JButton jButtonopen;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
